# Generated by Django 3.1.4 on 2020-12-10 17:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('quit_date', models.DateField(blank=True, default=None, null=True, verbose_name='Leave Date')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('severity', models.FloatField(verbose_name='Severity')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('footprints_number', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='FP#')),
                ('found_date', models.DateField(default=django.utils.timezone.now, verbose_name='Found Date')),
                ('committed_date', models.DateField(blank=True, default=None, null=True, verbose_name='Committed Date')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_coordinator', to='qa.employee', verbose_name='Coordinator')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_employee', to='qa.employee', verbose_name='Employee')),
                ('tags', models.ManyToManyField(to='qa.Tag', verbose_name='Tags')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.errortype', verbose_name='Error Type')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(to='qa.Role', verbose_name='Roles'),
        ),
    ]
