# Generated by Django 3.1.4 on 2020-12-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geek',
            name='quit_date',
            field=models.DateField(null=True),
        ),
    ]
