# Generated by Django 3.1.4 on 2020-12-09 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20201209_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('severity', models.FloatField(verbose_name='Severity')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='geek',
            name='hire_date',
            field=models.DateField(verbose_name='Hire Date'),
        ),
        migrations.AlterField(
            model_name='geek',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='geek',
            name='quit_date',
            field=models.DateField(null=True, verbose_name='Quit Date'),
        ),
        migrations.AlterField(
            model_name='geek',
            name='roles',
            field=models.ManyToManyField(to='qa.Role', verbose_name='Roles'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('footprints_number', models.CharField(max_length=10, verbose_name='FP#')),
                ('found_date', models.DateField(null=True, verbose_name='Found Date')),
                ('committed_date', models.DateField(verbose_name='Committed Date')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_coordinator', to='qa.geek', verbose_name='Coordinator')),
                ('geeks', models.ManyToManyField(to='qa.Geek', verbose_name='Geeks')),
                ('tags', models.ManyToManyField(to='qa.Tag', verbose_name='Tags')),
                ('type', models.ManyToManyField(to='qa.ErrorType', verbose_name='Error Type')),
            ],
        ),
    ]
