# Generated by Django 3.1.4 on 2020-12-09 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20201209_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='found_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 16, 35, 59, 401270), verbose_name='Found Date'),
        ),
    ]
