# Generated by Django 3.1.4 on 2020-12-09 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_auto_20201209_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='committed_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Committed Date'),
        ),
        migrations.AlterField(
            model_name='error',
            name='footprints_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='FP#'),
        ),
        migrations.AlterField(
            model_name='error',
            name='found_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 9, 16, 37, 35, 499965), verbose_name='Found Date'),
        ),
    ]
